"""Tests for the shared non-clobber predicate, the v3 store path helper, and
the version-aware launch-guidance helper.

Pure units plus a file-content agreement test across the three doc surfaces
(`README.md`, `quoin/CLAUDE.md`, `quoin/memory/workflow-catalog.md`). No
network, no subprocess.
"""
from __future__ import annotations

import builtins
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT / "src"))

from quoin.ccr_config import (  # noqa: E402
    OPENROUTER_PREFIX,
    UNKNOWN_LAUNCH_NOTE,
    V2_LAUNCH_COMMAND,
    V3_LAUNCH_COMMAND,
    V3_PROFILE_NAME,
    ccr_config_path,
    ccr_store_path,
    launch_guidance,
    owned_key_is_writable,
)

# Doc surfaces live under REPO_ROOT (README.md) and REPO_ROOT/"quoin" (the
# source package dir that also holds CLAUDE.md and memory/workflow-catalog.md).


# ── owned_key_is_writable ────────────────────────────────────────────────────


def test_owned_key_is_writable_absent():
    assert owned_key_is_writable(None) is True


def test_owned_key_is_writable_openrouter_prefixed():
    assert owned_key_is_writable("openrouter,some-model") is True


def test_owned_key_is_writable_foreign():
    assert owned_key_is_writable("my-provider,my-model") is False


def test_owned_key_is_writable_non_string():
    assert owned_key_is_writable(123) is False
    assert owned_key_is_writable({"a": 1}) is False


def test_owned_key_is_writable_uses_build_router_map_prefix():
    # Mirrors the construction models.build_router_map uses.
    slug = "z-ai/glm-4.6"
    value = f"{OPENROUTER_PREFIX}{slug}"
    assert owned_key_is_writable(value) is True


# ── ccr_store_path ───────────────────────────────────────────────────────────


def test_ccr_store_path_matches_config_dir(tmp_path):
    config = ccr_config_path(home=tmp_path)
    store = ccr_store_path(home=tmp_path)
    assert store == config.parent / "config.sqlite"


def test_ccr_store_path_does_not_touch_disk(tmp_path, monkeypatch):
    calls = []
    real_open = builtins.open
    real_os_open = os.open

    def _tracking_open(*args, **kwargs):
        calls.append(("open", args, kwargs))
        return real_open(*args, **kwargs)

    def _tracking_os_open(*args, **kwargs):
        calls.append(("os.open", args, kwargs))
        return real_os_open(*args, **kwargs)

    monkeypatch.setattr(builtins, "open", _tracking_open)
    monkeypatch.setattr(os, "open", _tracking_os_open)

    result = ccr_store_path(home=tmp_path)

    assert calls == []
    assert not result.exists()


# ── launch_guidance ──────────────────────────────────────────────────────────


def test_launch_guidance_v3_names_profile():
    cmd, note = launch_guidance(3)
    assert cmd == V3_LAUNCH_COMMAND
    assert V3_PROFILE_NAME in note
    assert "configure its models" in note
    assert "routes nothing" in note  # does not claim it routes
    assert "ccr code" not in note


def test_launch_guidance_v2_is_todays_command():
    cmd, note = launch_guidance(2)
    assert cmd == V2_LAUNCH_COMMAND
    assert note == ""


def test_launch_guidance_unknown_declines():
    for major in (None, 0, 4):
        cmd, note = launch_guidance(major)
        assert cmd == ""
        assert note == UNKNOWN_LAUNCH_NOTE


def test_launch_guidance_returns_a_pair():
    for major in (None, 0, 2, 3, 4):
        result = launch_guidance(major)
        assert isinstance(result, tuple)
        assert len(result) == 2
        assert all(isinstance(part, str) for part in result)


# ── doc-surface agreement ───────────────────────────────────────────────────


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_three_doc_surfaces_agree_with_helper():
    surfaces = [
        REPO_ROOT / "README.md",
        REPO_ROOT / "quoin" / "CLAUDE.md",
        REPO_ROOT / "quoin" / "memory" / "workflow-catalog.md",
    ]
    texts = [_read(p) for p in surfaces]

    v2_cmd, _ = launch_guidance(2)
    v3_cmd, _ = launch_guidance(3)

    for path, text in zip(surfaces, texts):
        assert v2_cmd in text, f"{path} missing v2 command {v2_cmd!r}"
    for path, text in zip(surfaces, texts):
        assert v3_cmd in text, f"{path} missing v3 command {v3_cmd!r}"


def test_readme_names_both_paths():
    text = _read(REPO_ROOT / "README.md")
    assert V2_LAUNCH_COMMAND in text
    assert V3_LAUNCH_COMMAND in text

    idx = text.index(V3_LAUNCH_COMMAND)
    window = text[max(0, idx - 500): idx + 500]
    assert "configure its models" in window
    assert "routes nothing" in window  # does not claim it routes


def test_catalog_is_generated_from_claude_md():
    catalog_text = _read(REPO_ROOT / "quoin" / "memory" / "workflow-catalog.md")
    first_line = catalog_text.splitlines()[0]
    assert "generated by" in first_line

    claude_md_text = _read(REPO_ROOT / "quoin" / "CLAUDE.md")
    # The open-model routing section starts at the "Open-model routing" heading
    # and runs to the next top-level heading.
    start = claude_md_text.index("Open-model routing")
    rest = claude_md_text[start:]
    next_heading = rest.find("\n## ", 1)
    section = rest if next_heading == -1 else rest[:next_heading]
    assert section.strip() in catalog_text
